databases:
  default:
    ENGINE: 'django.db.backends.sqlite3'
    NAME: '../../db.sqlite3'

aws:
  # AWS Educate 특성상 credential을 이용하는 IAM User를 사용할 수 없으므로
  # IAM Role, Instance profile을 이용합니다. 따라서 EC2에서는 credential을 설정할 필요 없습니다.
  # 로컬의 경우 $ aws configure를 통해 설정할 것.
  s3_enabled: false
  region: ""
  bucket_name: ""
  default_acl: ""
